In [1]:
import numpy as np
a=[1,2,3,4,5]
b=[5,6,7,8,4]
[a[i]*b[i] for i in range(len(b))]

[5, 12, 21, 32, 20]

In [2]:
import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
a+b

array([ 6,  8, 10, 12])

In [4]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [5]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr[0:,2:]

array([[3],
       [6],
       [9]])

In [49]:
c=np.eye(3,3)
c.dtype


dtype('float64')

In [52]:
c.astype("int32").dtype

dtype('int32')

In [45]:
c*arr

array([[1., 0., 0.],
       [0., 5., 0.],
       [0., 0., 9.]])

In [53]:
c.dtype

dtype('float64')

In [56]:
np.zeros((2,2))# array of zeros

array([[0., 0.],
       [0., 0.]])

In [60]:
a=np.arange(10)  #range

In [62]:
a[a>2]

array([3, 4, 5, 6, 7, 8, 9])

In [65]:
np.arange(10,20,5)

array([10, 15])

In [69]:
np.linspace(0,10,5)  # it will wtite numbers from 0 to 10 of 5 numbers which are equla differences(equal partition)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [70]:
##vector operations with scalar values         (2,3,=scalr     [1,2,3]=vector)

In [72]:
a=np.array([1,2,3])
a**2

array([1, 4, 9])

In [77]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
a,b

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [78]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [79]:
a+b

array([[ 6,  8],
       [10, 12]])